Vagrant.configure("2") do |config|

  config.vm.define :drood_vm do |drood_config|
    # Every Vagrant virtual environment requires a box to build off of.
    drood_config.vm.box = "puppetlabs/ubuntu-14.04-64-puppet"
    #drood_config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-i386-vagrant-disk1.box"
    drood_config.vm.hostname = "drood.placeholder.com"

    # Forward a port from the guest to the host, which allows for outside
    # computers to access the VM, whereas host only networking does not.
    drood_config.vm.network :forwarded_port, host: 9171, guest: 8001	

    drood_config.vm.synced_folder "../", "/vagrant", id: "1",
          mount_options: ["dmode=775", "fmode=764"]
  
    drood_config.vm.provision :shell do |shell|
      shell.path = "shell/main.sh"
    end

    drood_config.vm.provision :puppet do |puppet|
      puppet.manifests_path = 'puppet/manifests'
      puppet.manifest_file  = "default.pp"
      puppet.module_path    = ['puppet/modules', 'puppet/modules-contrib']
    end

  end
end

